In [2]:
#Abrimos la carpeta donde se encuentran las bases de datos

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
!pip install pyreadstat
import pyreadstat as py

Requirement already satisfied: pyreadstat in /opt/anaconda3/lib/python3.12/site-packages (1.2.8)
Requirement already satisfied: pandas>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from pyreadstat) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadstat) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadstat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadstat) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadstat) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.16.0)

In [3]:
import os
print(os.getcwd())  # Muestra la ruta actual de trabajo
print(os.listdir())  # Lista todos los archivos en el directorio actual

/Users/arielamirmelstein/Desktop/Ciencia de datos/Tutorial8
['Tutorial8.ipynb', 'market.csv', 'TP·4,,.ipynb', '.ipynb_checkpoints', 'TP3.2.ipynb']

In [4]:
os.chdir("/Users/arielamirmelstein/Documents/GitHub/CC408--T2-9-/TP3")
print(os.listdir())  # Verifica que el archivo esté en esta carpeta

['.DS_Store', 'Untitled.ipynb', 'norespondieron.csv', 'TP·4.ipynb', 'TP3.1.ipynb', 'respondieron.csv', 'Individual_t104 copy.dta', 'TP·4,,.ipynb', 'usu_individual_T124 copy.xlsx', '.ipynb_checkpoints', 'EPH_disenoreg_T1_2004.pdf', 'TP3.2.ipynb', 'EPH_registro_1T2024.pdf']

In [5]:
# Cargo archivo DTA
df_2004 = pd.read_stata("Individual_t104 copy.dta")
print(df_2004.head())
#aglomerados de Ciudad Autónoma de Buenos Aires (32) y Gran Buenos Aires (33)
df_2004.drop(df_2004[df_2004["aglomerado"].isin([32, 33])].index, inplace=True)


# Cambiamos los nombres de las columnas a minúsculas
df_2004.columns = df_2004.columns.str.lower()

df_2004

     CODUSU  nro_hogar componente h15    ano4       trimestre  \
0  125098          1.0        1.0  Sí  2004.0  1er. Trimestre
1  125397          1.0        1.0  Sí  2004.0  1er. Trimestre
2  125515          1.0        1.0  Sí  2004.0  1er. Trimestre
3  125558          1.0        1.0  Sí  2004.0  1er. Trimestre
4  125558          1.0        2.0  Sí  2004.0  1er. Trimestre

              region mas_500              aglomerado  pondera  ... deccfr  \
0  Gran Buenos Aires       S  Ciudad de Buenos Aires   1299.0  ...     07
1  Gran Buenos Aires       S  Ciudad de Buenos Aires   2018.0  ...     00
2  Gran Buenos Aires       S  Ciudad de Buenos Aires   1486.0  ...     07
3  Gran Buenos Aires       S  Ciudad de Buenos Aires   1674.0  ...     08
4  Gran Buenos Aires       S  Ciudad de Buenos Aires   1674.0  ...     08

  ideccfr rdeccfr gdeccfr pdeccfr adeccfr pj1_1 pj2_1 pj3_1 idimpp
0              06      06              04   0.0   0.0   0.0  00000
1              00      00              00   0.0   0.0   0.0  00000
2              07      07              05   0.0   0.0   0.0  00020
3              08      08              06   0.0   0.0   0.0  00000
4              08      08              06   0.0   0.0   0.0  00000

[5 rows x 176 columns]

,codusu,nro_hogar,componente,h15,ano4,trimestre,region,mas_500,aglomerado,pondera,...,deccfr,ideccfr,rdeccfr,gdeccfr,pdeccfr,adeccfr,pj1_1,pj2_1,pj3_1,idimpp
0,125098,1.0,1.0,Sí,2004.0,1er. Trimestre,Gran Buenos Aires,S,Ciudad de Buenos Aires,1299.0,...,07,,06,06,,04,0.0,0.0,0.0,00000
1,125397,1.0,1.0,Sí,2004.0,1er. Trimestre,Gran Buenos Aires,S,Ciudad de Buenos Aires,2018.0,...,00,,00,00,,00,0.0,0.0,0.0,00000
2,125515,1.0,1.0,Sí,2004.0,1er. Trimestre,Gran Buenos Aires,S,Ciudad de Buenos Aires,1486.0,...,07,,07,07,,05,0.0,0.0,0.0,00020
3,125558,1.0,1.0,Sí,2004.0,1er. Trimestre,Gran Buenos Aires,S,Ciudad de Buenos Aires,1674.0,...,08,,08,08,,06,0.0,0.0,0.0,00000
4,125558,1.0,2.0,Sí,2004.0,1er. Trimestre,Gran Buenos Aires,S,Ciudad de Buenos Aires,1674.0,...,08,,08,08,,06,0.0,0.0,0.0,00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45284,285733,1.0,1.0,Sí,2004.0,1er. Trimestre,Patagónica,N,Ushuaia - Río Grande,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45285,285733,1.0,2.0,Sí,2004.0,1er. Trimestre,Patagónica,N,Ushuaia - Río Grande,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45286,285733,1.0,3.0,Sí,2004.0,1er. Trimestre,Patagónica,N,Ushuaia - Río Grande,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45287,285733,1.0,4.0,0.0,2004.0,1er. Trimestre,Patagónica,N,Ushuaia - Río Grande,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45288,285733,1.0,5.0,0.0,2004.0,1er. Trimestre,Patagónica,N,Ushuaia - Río Grande,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000

In [ ]:
# Cargo el archivo xlsx
df_2024 = pd.read_excel("usu_individual_T124 copy.xlsx") 

print(df_2024.head())
# aglomerados de Ciudad Autónoma de Buenos Aires (32) y Gran Buenos Aires (33)
df_2024.drop(df_2024[df_2024["AGLOMERADO"].isin([32, 33])].index, inplace=True)


# Cambiamos los nombres de las columnas a minúsculas
df_2024.columns = df_2024.columns.str.lower()

df_2024

In [ ]:
diferentes_1 = set(df_2004.columns) - set(df_2024.columns)  # Columnas que están en df_2004 pero no en df_2024
diferentes_2 = set(df_2024.columns) - set(df_2004.columns)  # Columnas que están en df_2024 pero no en df_2004

print(f"Columnas en df_2004 pero no en df_2024: {diferentes_1}")
print(f"Columnas en df_2024 pero no en df_2004: {diferentes_2}")

In [ ]:
df_2004 = df_2004.drop(columns=['pj3_1', 'pj1_1', 'idimpp', 'pj2_1'])
df_2024 = df_2024.drop(columns=['imputa', 'pondii', 'pondiio', 'pondih', 'ch05'])

In [ ]:
# Agregar una columna para identificar el año en df_2004
df_2004['anio'] = 2004

# Agregar una columna para identificar el año en df_2024
df_2024['anio'] = 2024

In [ ]:
df_conjunto = pd.concat([df_2004, df_2024], axis=0)
# Ver el DataFrame resultante
print(df_conjunto)

In [ ]:
print(df_conjunto.columns)

In [ ]:
df_conjunto.describe()
#despues de esto saco los negativos y los NAN

In [ ]:
# 'ch04' es la columna que indica el sexo y 'ano4' es la columna para el año.
# Calcular la composición por sexo para cada año
composicion_sexo_2004 = df_2004['ch04'].value_counts(normalize=True) * 100  # Porcentajes
composicion_sexo_2024 = df_2024['ch04'].value_counts(normalize=True) * 100  # Porcentajes

# Renombrar los índices de la composición de 2024
composicion_sexo_2024.index = composicion_sexo_2024.index.map({1: 'Varón', 2: 'Mujer'})

# resultado de porcentaje sexos por año
print("\nComposición por sexo en 2004 y 2024:")
for year, composicion in zip(['2004', '2024'], [composicion_sexo_2004, composicion_sexo_2024]):
    print(f"\nComposición por sexo en {year}:")
    for sexo, porcentaje in composicion.items():
        print(f"{sexo}: {porcentaje:.2f}%")

In [ ]:
# Crear un DataFrame para el gráfico
df_composicion = pd.DataFrame({
    '2004': composicion_sexo_2004,
    '2024': composicion_sexo_2024
})

# Configurar gráfico de barras
df_composicion.plot(kind='bar', color=['blue', 'red'], width=0.7)
plt.title("Composición por Sexo en 2004 y 2024")
plt.xlabel("Sexo")
plt.ylabel("Porcentaje")
plt.legend(title="Año")
plt.xticks(rotation=0)
plt.show()

In [ ]:
#Matriz correlación 

variables = ['ch04', 'ch06', 'ch07', 'ch08', 'nivel_ed', 'estado', 'cat_inac', 'ipcf']
print("Columnas en df_conjunto:", df_conjunto.columns)

# chequeo que todas las columnas para la matriz están presentes
missing_columns = [col for col in variables if col not in df_conjunto.columns]
if missing_columns:
    print("Columnas faltantes:", missing_columns)
else:
    print("Todas las columnas necesarias están presentes.")

In [ ]:
# Identificar columnas que contienen valores de tipo string, es decir no numericas, para despues ocupanos de pasarlas a numericas 
string_columns = [col for col in variables if df_2004[col].apply(lambda x: isinstance(x, str)).any()]

if string_columns:
    print("Las siguientes columnas contienen valores de tipo string:", string_columns)
else:
    print("No hay columnas de tipo string en las variables de interés.")

In [ ]:
# Define los mapeos de conversión para cada columna
conversiones = {
    'ch04': {
        'Varón': 1,
        'Mujer': 2,
    },
    'ch06': {
        'Menos de 1 año': 0,
        '1-2 años': 1,
        '3-5 años': 2,
        'Más de 5 años': 3,
        '98 y más años': 4,
    },
    'nivel_ed': {
        'Primaria incompleto (incluye educación especial)': 1,
        'Primaria Completa': 2,
        'Secundaria Incompleta': 3,
        'Secundaria completo': 4,
        'Superior universitario incompleto': 5,
        'Superior Universitaria Completa': 6,
        'Sin instrucción': 7,
        'Ns./Nr.': 9
    },
    'ch08': {
        'Obra social (incluye PAMI)': 1,
        'Mutual/Prepaga/Servicio de emergencia': 2,
        'Planes y seguros públicos': 3,
        'No paga ni le descuentan': 4,
        'Ns./Nr.': 9,
        'Obra social y mutual / prepaga / servicio de emergencia': 12,
        'Obra social y planes y seguros públicos': 13,
        'Mutual/prepaga/ servicio de emergencia/Planes y seguros públicos': 23,
        'Obra social, mutual /prepaga / servicio de emergencia y planes y seguros públicos': 123
    },
    'estado': {
        'Entrevista individual no realizada (no respuesta al cuestion': 0, 
        'Ocupado': 1,
        'Desocupado': 2,
        'Inactivo': 3,
        'Menor de 10 años': 4
    },
    'cat_inac': {
        'Jubilado/pensionado': 1,
        'Rentista': 2,
        'Estudiante': 3,
        'Ama de casa': 4,
        'Menor de 6 años': 5,
        'Discapacitado': 6,
        'Otros': 7,
        0: 8  # Manejo del valor 0.0
    },
    'ch07': {
        'Unido': 1,
        'Casado': 2,
        'Separado o divorciado': 3,
        'Viudo': 4,
        'Soltero': 5,
        9: None  # Si deseas tratar el 9 como NaN, puedes usar None
    }
}

# Aplica la conversión a cada columna
for col, mapa in conversiones.items():
    if col in df_2004.columns:
        df_2004[col] = df_2004[col].replace(mapa)

# Verifica las conversiones
print(df_2004[variables].head())

In [ ]:
# Identificar columnas que contienen valores de tipo string, es decir no numericas, para despues ocupanos de pasarlas a numericas 
string_columns2 = [col for col in variables if df_2024[col].apply(lambda x: isinstance(x, str)).any()]

if string_columns2:
    print("Las siguientes columnas contienen valores de tipo string:", string_columns2)
else:
    print("No hay columnas de tipo string en las variables de interés.")

In [ ]:
df_conjunto = pd.concat([df_2004, df_2024], ignore_index=True)

In [ ]:
# Identificar columnas que contienen valores de tipo string, es decir no numericas, para despues ocupanos de pasarlas a numericas 
string_columns3 = [col for col in variables if df_conjunto[col].apply(lambda x: isinstance(x, str)).any()]

if string_columns3:
    print("Las siguientes columnas contienen valores de tipo string:", string_columns3)
else:
    print("No hay columnas de tipo string en las variables de interés.")

In [ ]:
# Define los mapeos de conversión para cada columna
conversiones = {
    'nivel_ed': {
        'Primaria Incompleta (incluye educación especial)': 1,
        'Primaria Completa': 2,
        'Secundaria Incompleta': 3,
        'Secundaria Completa': 4,
        'Superior Universitaria Incompleta': 5,
        'Superior Universitaria Completa': 6,
        'Sin instrucción': 7,
        'Ns./Nr.': 9
    },
    'ch08': {
        'Obra social (incluye PAMI)': 1,
        'Mutual/Prepaga/Servicio de emergencia': 2,
        'Planes y seguros públicos': 3,
        'No paga ni le descuentan': 4,
        'Ns./Nr.': 9,
        'Obra social y mutual/prepaga/servicio de emergencia': 12,
        'Obra social y planes y seguros públicos': 13,
        'Mutual/prepaga/servicio de emergencia/planes y seguros públi': 23,
        'Obra social, mutual/prepaga/servicio de emergencia y planes': 123
    },
    'ch07': {
        'Unido': 1,
        'Casado': 2,
        'Separado o divorciado': 3,
        'Viudo': 4,
        'Soltero': 5,
        'Ns./Nr.':6,
        9: None  # Si deseas tratar el 9 como NaN, puedes usar None
    }
}

# Aplica la conversión a cada columna
for col, mapa in conversiones.items():
    if col in df_conjunto.columns:
        df_conjunto[col] = df_conjunto[col].replace(mapa)

# Verifica las conversiones
print(df_conjunto[variables].head())

In [ ]:
# Identificar columnas que contienen valores de tipo string, es decir no numericas, para despues ocupanos de pasarlas a numericas 
string_columns3 = [col for col in variables if df_conjunto[col].apply(lambda x: isinstance(x, str)).any()]

if string_columns3:
    print("Las siguientes columnas contienen valores de tipo string:", string_columns3)
else:
    print("No hay columnas de tipo string en las variables de interés.")

In [ ]:
df_conjunto = pd.concat([df_2004, df_2024], axis=0)

# Asegúrate de que 'variables' contiene las columnas que deseas analizar
datos_filtrados = df_conjunto[variables]

# Convierte las columnas seleccionadas en 'variables' a numéricas, forzando errores a NaN
datos_filtrados = datos_filtrados.apply(pd.to_numeric, errors='coerce')

# Calcula la matriz de correlación
corr = datos_filtrados.corr()

# Crear un gráfico de calor para la correlación
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', vmin=-1, vmax=1, square=True)
plt.title('Matriz de correlación de las variables')
plt.show()

In [ ]:
# Matriz de correlacion + el mapa de calor
plt.figure(figsize=(10, 8))  # Ajusta el tamaño de la figura según sea necesario
ax = sns.heatmap(
    corr, 
    vmin=-1, vmax=1, center=0,
    cmap=sns.diverging_palette(20, 220, n=200),
    square=True,
    annot=True,  # Para mostrar los valores de correlación en cada celda
    fmt=".2f"   # Formato de los valores en el mapa
)

# Configura las etiquetas de los ejes
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
)
ax.set_yticklabels(
    ax.get_yticklabels(),
    rotation=0,
    horizontalalignment='right'
)

# Muestra el mapa de calor
plt.title('Matriz de Correlación de Variables')
plt.show()

In [ ]:
# Matriz de correlacion + el mapa de calor
plt.figure(figsize=(10, 8))  # Ajusta el tamaño de la figura según sea necesario
ax = sns.heatmap(
    corr, 
    vmin=-1, vmax=1, center=0,
    cmap=sns.diverging_palette(20, 220, n=200),
    square=True,
    annot=True,  # Para mostrar los valores de correlación en cada celda
    fmt=".2f"   # Formato de los valores en el mapa
)

# Configura las etiquetas de los ejes
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
)
ax.set_yticklabels(
    ax.get_yticklabels(),
    rotation=0,
    horizontalalignment='right'
)

# Muestra el mapa de calor
plt.title('Matriz de Correlación de Variables')
plt.show()

In [ ]:
# Mejoramos la visualización de las correlaciones de la matriz 
datos_filtrados = datos_filtrados.apply(pd.to_numeric, errors='coerce')

# Calcular la matriz de correlación
corr = datos_filtrados.corr()

# Unpivot the dataframe, so we can get pairs of arrays for x and y
corr_melted = pd.melt(corr.reset_index(), id_vars='index') 
corr_melted.columns = ['x', 'y', 'value']

# Configuración de la paleta de colores
n_colors = 256  # Número de colores para la paleta divergente
palette = sns.diverging_palette(20, 220, n=n_colors)  # Crear la paleta
color_min, color_max = [-1, 1]  # Rango de valores que se mapearán a la paleta

# Función para mapear valores a colores
def value_to_color(val):
    val_position = float((val - color_min)) / (color_max - color_min)  # Posición del valor en el rango de entrada
    ind = int(val_position * (n_colors - 1))  # Índice objetivo en la paleta de colores
    return palette[ind]

# Define la función heatmap
def heatmap(x, y, size, color):
    fig, ax = plt.subplots(figsize=(10, 8))
    
    # Mapping from column names to integer coordinates
    x_labels = [v for v in sorted(x.unique())]
    y_labels = [v for v in sorted(y.unique())]
    x_to_num = {p[1]: p[0] for p in enumerate(x_labels)} 
    y_to_num = {p[1]: p[0] for p in enumerate(y_labels)} 
    
    size_scale = 500
    ax.scatter(
        x=x.map(x_to_num),  # Use mapping for x
        y=y.map(y_to_num),  # Use mapping for y
        s=size * size_scale,  # Vector de tamaños de cuadrado, proporcional al parámetro size
        c=color.apply(value_to_color),  # Vector de colores de cuadrados, mapeado a la paleta de colores
        marker='s'  # Usar cuadrado como marcador de dispersión
    )
    
    # Show column labels on the axes
    ax.set_xticks([x_to_num[v] for v in x_labels])
    ax.set_xticklabels(x_labels, rotation=45, horizontalalignment='right')
    ax.set_yticks([y_to_num[v] for v in y_labels])
    ax.set_yticklabels(y_labels)
    
    plt.title('Matriz de correlación visualizada como scatter plot')
    plt.grid()
    plt.show()

# Llama a la función heatmap con tus datos de correlación
heatmap(
    x=corr_melted['x'],
    y=corr_melted['y'],
    size=corr_melted['value'].abs(),  # Usa el valor absoluto para el tamaño
    color=corr_melted['value']  # Usa los valores de correlación para el color
)

In [ ]:

# Contar la cantidad de desocupados (estado == 2) e inactivos (estado == 3)
cantidad_desocupados = df_conjunto[df_conjunto['estado'] == 2].shape[0]
cantidad_inactivos = df_conjunto[df_conjunto['estado'] == 3].shape[0]

total = len(df_conjunto)

print(f"La cantidad de desocupados es {cantidad_desocupados}")
print(f"Representa un {round(cantidad_desocupados / total * 100, 2)}% del total")

print(f"La cantidad de inactivos es {cantidad_inactivos}")
print(f"Representa un {round(cantidad_inactivos / total * 100, 2)}% del total")

In [ ]:
# Media de ingreso per cápita familiar (IPCF) según estado
media_ipcf_por_estado = df_conjunto.groupby('estado')['ipcf'].mean()

# Mostrar media de IPCF
print("\nMedia de ingreso per cápita familiar (ipcf) según estado:")
print(media_ipcf_por_estado)

In [ ]:
df_conjunto['estado'].unique()

In [ ]:
#ejercicio 3
#Crear un DataFrame con las observaciones donde estado es 0, osea 'Entrevista individual no realizada (no respuesta al cuestion'
no_respondieron = df_conjunto[df_conjunto['estado'] == 0]
no_respondieron.shape[0]

# Miro cuántas personas no respondieron su condición de actividad
no_respondieron = no_respondieron.shape[0]  # Esta variable contendrá la cantidad de personas
print(f"La cantidad de personas que no respondieron su condición de actividad es: {no_respondieron}")

In [ ]:
# Crear un DataFrame con las observaciones donde estado no es 0
respondieron = df_conjunto[df_conjunto['estado'] != 0]  # Asegúrate de que esto se mantenga como un DataFrame
respondieron = respondieron.shape[0]  # Esta variable contendrá la cantidad de personas
print(f"La cantidad de personas que sí respondieron su condición de actividad es: {respondieron}")

In [ ]:
# Definir los valores que son PEA
estados_pea = [1, 2]  # Ocupado y Desocupado

# Imprimir tipos de datos y valores únicos para depuración
print("Tipo de datos de 'estado':", respondieron['estado'].dtype)
print("Valores únicos en 'estado':", respondieron['estado'].unique())

# Crear la columna PEA en el DataFrame `respondieron`
try:
    respondieron['PEA'] = respondieron['estado'].apply(lambda x: 1 if x in estados_pea else 0)
except Exception as e:
    print("Error al crear la columna PEA:", e)

# Filtrar los datos por año
pea_2004 = respondieron[respondieron['anio'] == 2004]['PEA'].value_counts()
pea_2024 = respondieron[respondieron['anio'] == 2024]['PEA'].value_counts()

# Crear un DataFrame con la información para el gráfico
pea_data = pd.DataFrame({
    '2004': pea_2004,
    '2024': pea_2024
}).transpose()

# Graficar los datos
pea_data.plot(kind='bar', stacked=True, color=['lightblue', 'salmon'])
plt.title('Composición por Población Económicamente Activa (PEA) en 2004 y 2024')
plt.xlabel('Año')
plt.ylabel('Cantidad')
plt.xticks(ticks=[0, 1], labels=['No PEA', 'PEA'], rotation=0)  # Ajusta las etiquetas del eje x
plt.legend(title='Estado PEA', labels=['No PEA', 'PEA'])
plt.show()

In [ ]:
#ejercicio 4

# Confirmar los valores únicos en `estado` en el DataFrame `respondieron`
print("Valores únicos en la columna estado:", respondieron["estado"].unique())
# esta ok por que elimino el 0 osea los 'Entrevista individual no realizada (no respuesta al cuestion"

In [ ]:
# Convertir la columna `PEA` según los valores numéricos
# Supongamos que "Ocupado" corresponde a 1 y "Desocupado" a 2 (según tu asignación previa)
respondieron.loc[:, "PEA"] = respondieron["estado"].apply(lambda x: 1 if x in [1, 2] else 0)

# Verifica los valores únicos en la nueva columna `PEA`
print("Valores únicos en la columna PEA:", respondieron["PEA"].unique())

In [ ]:
# Filtrar los dataframes para 2004 y 2024
respondieron_2004 = respondieron[respondieron['anio'] == 2004]
respondieron_2024 = respondieron[respondieron['anio'] == 2024]

# Contar la cantidad de PEA en cada año
pea_counts = pd.DataFrame({
    'Ano4': ['2004', '2024'],
    'PEA': [respondieron_2004['PEA'].sum(), respondieron_2024['PEA'].sum()],
    'No PEA': [respondieron_2004['PEA'].count() - respondieron_2004['PEA'].sum(),
               respondieron_2024['PEA'].count() - respondieron_2024['PEA'].sum()]
})

In [ ]:
# Graficar
pea_counts.set_index('Ano4').plot(kind='bar', stacked=True)
plt.title('Composición por Población Económicamente Activa (PEA)')
plt.ylabel('Cantidad de personas')
plt.xlabel('Ano4')
plt.xticks(rotation=0)
plt.legend(title='Estado', labels=['PEA', 'No PEA'])
plt.show()

In [ ]:
print("PEA para 2024:", respondieron_2024['PEA'].sum())
print("No PEA para 2024:", respondieron_2024['PEA'].count() - respondieron_2024['PEA'].sum())

In [ ]:
#ejercicio 5
respondieron["ch06"].unique()

In [ ]:

# Convertir la columna 'ch06' a numérico
respondieron['ch06'] = pd.to_numeric(respondieron['ch06'], errors='coerce')

# Crear la columna PET
respondieron['PET'] = respondieron['ch06'].apply(lambda x: 1 if 15 <= x <= 65 else 0)

In [ ]:
pea_pet_counts = pd.DataFrame({
    'Año': ['2004', '2024'],
    'PEA': [150, 180],  # Sustituye por los valores reales
    'PET': [200, 220]   # Sustituye por los valores reales
})

# Configurar el gráfico
bar_width = 0.35
index = range(len(pea_pet_counts))

# Crear el gráfico de barras
plt.bar(index, pea_pet_counts['PEA'], bar_width, label='PEA')
plt.bar([i + bar_width for i in index], pea_pet_counts['PET'], bar_width, label='PET')

# Añadir etiquetas y título
plt.xlabel('Año')
plt.ylabel('Cantidad')
plt.title('Composición por PEA y PET para 2004 y 2024')
plt.xticks([i + bar_width / 2 for i in index], pea_pet_counts['Año'])
plt.legend()

# Mostrar el gráfico
plt.tight_layout()
plt.show()

In [ ]:
print(respondieron['estado'].unique())

In [ ]:
#ejercicio 6
# Revisar los valores únicos y sus frecuencias en 'estado'
print(respondieron['estado'].value_counts())

In [ ]:
# Crear la columna 'desocupado' ajustando según los valores confirmados de 'estado'
respondieron['desocupado'] = respondieron['estado'].apply(lambda x: 1 if x in [1, 2] else 0)

# Contar el número de personas desocupadas por año
desocupados_counts = respondieron.groupby('anio')['desocupado'].sum().reset_index()

# Mostrar el resultado
print(desocupados_counts)